/// Memory model for Kairos app.
///
/// Represents a post-experience record capturing photos, text, place, music,
/// and mood. Memories can be linked to planned moments or standalone.
///
/// Each memory is created by one partner but visible to both in a shared
/// timeline. Partner reactions are stored inline as a userId → emoji map.
library;

import 'package:cloud_firestore/cloud_firestore.dart';

// =============================================================================
// Enums
// =============================================================================

/// Lifecycle status for moments.
///
/// - [planned]: Default state; moment is scheduled or date has passed but no
///   memory/missed action taken.
/// - [lived]: At least one memory has been created for this moment.
/// - [missed]: User explicitly marked the moment as "didn't happen".
enum MomentStatus {
  planned('planned'),
  lived('lived'),
  missed('missed');

  const MomentStatus(this.value);

  /// Firestore storage value.
  final String value;

  /// Creates a MomentStatus from its Firestore value.
  /// Defaults to [planned] for unknown or null values.
  static MomentStatus fromValue(String value) {
    return MomentStatus.values.firstWhere(
      (e) => e.value == value,
      orElse: () => MomentStatus.planned,
    );
  }
}

// =============================================================================
// Curated Reaction Emojis
// =============================================================================

/// The curated set of reaction emojis available for memories.
class MemoryReactions {
  MemoryReactions._();

  static const List<({String emoji, String label})> options = [
    (emoji: '❤️', label: 'Love'),
    (emoji: '😂', label: 'Funny'),
    (emoji: '🥹', label: 'Touched'),
    (emoji: '🔥', label: 'Fire'),
    (emoji: '🥰', label: 'Adoring'),
    (emoji: '✨', label: 'Amazing'),
  ];
}

// =============================================================================
// Memory Model
// =============================================================================

/// Represents a sealed memory within a couple space.
///
/// Memories capture a post-experience reflection: photos, caption, place, music,
/// and an optional embedded pulse check-in. They can be linked to a planned
/// [Moment] or created standalone for spontaneous experiences.
///
/// ## Document ID Convention
///
/// - Moment-linked: `{momentId}_{userId}` (enforces 1 per user per moment).
/// - Standalone: auto-generated by Firestore `.doc()`.
class Memory {
  const Memory({
    required this.id,
    required this.createdBy,
    required this.date,
    required this.createdAt,
    this.momentId,
    this.momentName,
    this.momentType,
    this.momentDate,
    this.momentEndDate,
    this.momentTimeSlot,
    this.momentNotes,
    this.title,
    this.photoPaths = const [],
    this.thumbPaths = const [],
    this.caption,
    this.place,
    this.music,
    this.checkinId,
    this.reactions = const {},
    this.updatedAt,
  });

  /// Unique identifier (Firestore document ID).
  final String id;

  // ---------------------------------------------------------------------------
  // Moment Link (null for standalone)
  // ---------------------------------------------------------------------------

  /// Linked moment ID, null for standalone memories.
  final String? momentId;

  /// Denormalized moment name at seal time.
  final String? momentName;

  /// Denormalized moment type at seal time ("connect" | "celebrate" | "escape").
  final String? momentType;

  /// Denormalized moment startDate at seal time.
  final DateTime? momentDate;

  /// Denormalized moment endDate at seal time (Escape moments only).
  final DateTime? momentEndDate;

  /// Denormalized moment timeSlot at seal time (Connect moments only).
  final String? momentTimeSlot;

  /// Denormalized moment notes at seal time.
  final String? momentNotes;

  // ---------------------------------------------------------------------------
  // Standalone Fields
  // ---------------------------------------------------------------------------

  /// User-provided title for standalone memories (max 100 chars).
  final String? title;

  // ---------------------------------------------------------------------------
  // Content
  // ---------------------------------------------------------------------------

  /// User ID of the creator.
  final String createdBy;

  /// Firebase Storage paths for full-size photos (max 3).
  final List<String> photoPaths;

  /// Firebase Storage paths for 300px thumbnails (max 3, parallel to [photoPaths]).
  final List<String> thumbPaths;

  /// Caption text (max 280 chars).
  final String? caption;

  /// Free-text place/location (max 100 chars).
  final String? place;

  /// Free-text song/artist (max 100 chars).
  final String? music;

  /// Linked UserCheckIn document ID (null if pulse sliders were not used).
  final String? checkinId;

  // ---------------------------------------------------------------------------
  // Social
  // ---------------------------------------------------------------------------

  /// Partner reactions: userId → emoji.
  final Map<String, String> reactions;

  // ---------------------------------------------------------------------------
  // Timestamps
  // ---------------------------------------------------------------------------

  /// When the experience happened (UTC midnight).
  final DateTime date;

  /// When the memory was sealed (server timestamp).
  final DateTime createdAt;

  /// Last edit timestamp, null if never edited.
  final DateTime? updatedAt;

  // ---------------------------------------------------------------------------
  // Computed
  // ---------------------------------------------------------------------------

  bool get isStandalone => momentId == null;
  bool get hasPhotos => photoPaths.isNotEmpty;
  bool get hasCheckin => checkinId != null;
  bool get isEdited => updatedAt != null;
  bool get hasCaption => caption != null && caption!.isNotEmpty;
  bool get hasPlace => place != null && place!.isNotEmpty;
  bool get hasMusic => music != null && music!.isNotEmpty;

  /// Whether any memory content fields have been filled.
  bool get hasContent => hasPhotos || hasCaption || hasPlace || hasMusic || hasCheckin;

  /// Display title: moment name for linked memories, user title for standalone.
  String get displayTitle => isStandalone ? (title ?? '') : (momentName ?? '');

  // ---------------------------------------------------------------------------
  // Factory Constructors
  // ---------------------------------------------------------------------------

  factory Memory.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data()! as Map<String, dynamic>;
    return Memory.fromJson(doc.id, data);
  }

  factory Memory.fromJson(String id, Map<String, dynamic> json) {
    return Memory(
      id: id,
      momentId: json['momentId'] as String?,
      momentName: json['momentName'] as String?,
      momentType: json['momentType'] as String?,
      momentDate: json['momentDate'] != null
          ? (json['momentDate'] as Timestamp).toDate()
          : null,
      momentEndDate: json['momentEndDate'] != null
          ? (json['momentEndDate'] as Timestamp).toDate()
          : null,
      momentTimeSlot: json['momentTimeSlot'] as String?,
      momentNotes: json['momentNotes'] as String?,
      title: json['title'] as String?,
      createdBy: json['createdBy'] as String? ?? '',
      photoPaths: List<String>.from(json['photoPaths'] ?? []),
      thumbPaths: List<String>.from(json['thumbPaths'] ?? []),
      caption: json['caption'] as String?,
      place: json['place'] as String?,
      music: json['music'] as String?,
      checkinId: json['checkinId'] as String?,
      reactions: Map<String, String>.from(json['reactions'] ?? {}),
      date: json['date'] != null
          ? (json['date'] as Timestamp).toDate()
          : DateTime.now().toUtc(),
      createdAt: json['createdAt'] != null
          ? (json['createdAt'] as Timestamp).toDate()
          : DateTime.now(),
      updatedAt: json['updatedAt'] != null
          ? (json['updatedAt'] as Timestamp).toDate()
          : null,
    );
  }

  // ---------------------------------------------------------------------------
  // Serialization
  // ---------------------------------------------------------------------------

  /// Converts to JSON for Firestore creation (seal).
  Map<String, dynamic> toJson() {
    return {
      if (momentId != null) 'momentId': momentId,
      if (momentName != null) 'momentName': momentName,
      if (momentType != null) 'momentType': momentType,
      if (momentDate != null) 'momentDate': Timestamp.fromDate(momentDate!),
      if (momentEndDate != null) 'momentEndDate': Timestamp.fromDate(momentEndDate!),
      if (momentTimeSlot != null) 'momentTimeSlot': momentTimeSlot,
      if (momentNotes != null) 'momentNotes': momentNotes,
      if (title != null) 'title': title,
      'createdBy': createdBy,
      'photoPaths': photoPaths,
      'thumbPaths': thumbPaths,
      if (caption != null) 'caption': caption,
      if (place != null) 'place': place,
      if (music != null) 'music': music,
      if (checkinId != null) 'checkinId': checkinId,
      'reactions': reactions,
      'date': Timestamp.fromDate(date),
      'createdAt': FieldValue.serverTimestamp(),
    };
  }

  /// Produces update payload for edits.
  /// Never touches createdAt, createdBy, reactions, checkinId, or moment fields.
  Map<String, dynamic> toUpdateJson() {
    return {
      'photoPaths': photoPaths,
      'thumbPaths': thumbPaths,
      if (caption != null) 'caption': caption else 'caption': FieldValue.delete(),
      if (place != null) 'place': place else 'place': FieldValue.delete(),
      if (music != null) 'music': music else 'music': FieldValue.delete(),
      if (title != null) 'title': title,
      'updatedAt': FieldValue.serverTimestamp(),
    };
  }

  // ---------------------------------------------------------------------------
  // Copy With
  // ---------------------------------------------------------------------------

  Memory copyWith({
    String? id,
    String? momentId,
    String? momentName,
    String? momentType,
    DateTime? momentDate,
    DateTime? momentEndDate,
    String? momentTimeSlot,
    String? momentNotes,
    String? title,
    String? createdBy,
    List<String>? photoPaths,
    List<String>? thumbPaths,
    String? caption,
    String? place,
    String? music,
    String? checkinId,
    Map<String, String>? reactions,
    DateTime? date,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Memory(
      id: id ?? this.id,
      momentId: momentId ?? this.momentId,
      momentName: momentName ?? this.momentName,
      momentType: momentType ?? this.momentType,
      momentDate: momentDate ?? this.momentDate,
      momentEndDate: momentEndDate ?? this.momentEndDate,
      momentTimeSlot: momentTimeSlot ?? this.momentTimeSlot,
      momentNotes: momentNotes ?? this.momentNotes,
      title: title ?? this.title,
      createdBy: createdBy ?? this.createdBy,
      photoPaths: photoPaths ?? this.photoPaths,
      thumbPaths: thumbPaths ?? this.thumbPaths,
      caption: caption ?? this.caption,
      place: place ?? this.place,
      music: music ?? this.music,
      checkinId: checkinId ?? this.checkinId,
      reactions: reactions ?? this.reactions,
      date: date ?? this.date,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() => 'Memory($id, ${displayTitle.isEmpty ? "untitled" : displayTitle})';
}
