// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJCeZ0r-StlWQXMsDI-j_wBcpNs-NAV0',
    appId: '1:459880996436:web:90b92f7b8ba9b734c857c1',
    messagingSenderId: '459880996436',
    projectId: 'couple-space-36e1a',
    authDomain: 'couple-space-36e1a.firebaseapp.com',
    storageBucket: 'couple-space-36e1a.firebasestorage.app',
    measurementId: 'G-4P61BD8130',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fbIs0fLxYJ3lvc6_ujqps9uR3WUNs6w',
    appId: '1:459880996436:android:4990d4d4d46b1757c857c1',
    messagingSenderId: '459880996436',
    projectId: 'couple-space-36e1a',
    storageBucket: 'couple-space-36e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOccQuU1ncrmz5LlxkbpY2tvo0zWVygvo',
    appId: '1:459880996436:ios:5989aedf72b53e1dc857c1',
    messagingSenderId: '459880996436',
    projectId: 'couple-space-36e1a',
    storageBucket: 'couple-space-36e1a.firebasestorage.app',
    iosBundleId: 'com.example.coupleSpace',
  );
}
